# Generated by Django 5.1.2 on 2024-11-28 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_rename_is_activate_user_is_active_and_more"),
        ("survey", "0009_alter_answer_token_alter_comment_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "organisations",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.organisation",
                    ),
                ),
                (
                    "surveys",
                    models.ManyToManyField(blank=True, to="survey.questionnaire"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="organisation",
            name="projects",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.project",
            ),
        ),
    ]
