# Generated by Django 5.1.4 on 2025-01-23 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_organisationmembership_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationmembership',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
