# Generated by Django 5.1.4 on 2025-03-07 15:56

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_project_description")
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="organisation",
            field=models.ForeignKey(
                null=True,  # Allow null temporarily
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="home.organisation",
            ),
        ),
    ]