# Generated by Django 5.1.4 on 2025-03-07 15:56
from django.db import migrations


def migrate_project_organisations(apps, schema_editor):
    """
    For each project, find its organization via the ProjectOrganisation table
    """
    Project = apps.get_model("home", "Project")
    Organisation = apps.get_model("home", "Organisation")

    # Get default organization or create one
    default_org = Organisation.objects.first()
    if not default_org:
        default_org = Organisation.objects.create(name="Default Organization")

    # Use raw SQL to get project-org mappings
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT project_id, organisation_id 
            FROM home_projectorganisation
        """
        )
        mappings = dict(cursor.fetchall())

    # Update each project
    for project in Project.objects.all():
        org_id = mappings.get(project.id)
        if org_id:
            try:
                org = Organisation.objects.get(id=org_id)
                project.organisation = org
            except Organisation.DoesNotExist:
                project.organisation = default_org
        else:
            project.organisation = default_org
        project.save()


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_add_org_field"),
    ]

    operations = [
        migrations.RunPython(migrate_project_organisations),
    ]
