# Generated by Django 5.1.4 on 2025-03-07 15:56
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_populate_org_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="home.organisation",
            ),
        ),
        # Delete ProjectManagerPermission table
        migrations.DeleteModel(
            name="ProjectManagerPermission",
        ),
        # Delete ProjectOrganisation table
        migrations.DeleteModel(
            name="ProjectOrganisation",
        ),
    ]
