# Generated by Django 5.1.4 on 2025-03-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_finalise_changes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="organisations",
        ),
    ]
