# Generated by Django 5.1.4 on 2025-03-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_remove_project_organisations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="created_on",
            new_name="created_at",
        ),
    ]
