# Generated by Django 5.1.13 on 2026-01-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_rename_created_on_project_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(help_text="Project title", max_length=100),
        ),
    ]
