# Generated by Django 5.1.13 on 2026-04-22 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_project_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataProtectionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("erasure", "Erasure request actioned"),
                            ("export", "Subject access export generated"),
                            ("restriction", "Account restricted / suspended"),
                            ("unrestriction", "Account restriction lifted"),
                            ("consent_withdrawal", "Consent withdrawn"),
                        ],
                        max_length=32,
                    ),
                ),
                ("subject_user_id", models.IntegerField(blank=True, null=True)),
                ("subject_identifier", models.CharField(max_length=254)),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("actioned_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "actioned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dp_events_actioned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dp_events_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-actioned_at",),
                "indexes": [
                    models.Index(
                        fields=["event_type", "-actioned_at"],
                        name="home_datapr_event_t_5ce3ce_idx",
                    ),
                    models.Index(
                        fields=["subject_user_id"],
                        name="home_datapr_subject_d52f32_idx",
                    ),
                ],
            },
        ),
    ]
