# Generated by Django 5.1.15 on 2026-02-12 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_project_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("DELETE_USER", "Delete User"),
                            ("DELETE_ORG", "Delete Organisation"),
                            ("DELETE_PROJECT", "Delete Project"),
                            ("DELETE_SURVEY", "Delete Survey"),
                            ("EXPORT_CONSENTED", "Export Consented Data"),
                            ("BULK_DELETE", "Bulk Delete"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("target_model", models.CharField(max_length=50)),
                ("target_id", models.IntegerField(null=True)),
                ("target_representation", models.CharField(max_length=200)),
                (
                    "reason",
                    models.TextField(
                        help_text="Explanation for why this action was taken"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional action details (e.g., cascade counts, export stats)",
                        null=True,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="home_admina_timesta_4adb99_idx"
                    ),
                    models.Index(
                        fields=["action_type"], name="home_admina_action__f02f66_idx"
                    ),
                    models.Index(
                        fields=["target_model", "target_id"],
                        name="home_admina_target__b98dbf_idx",
                    ),
                ],
            },
        ),
    ]
