# Generated by Django 5.1.15 on 2026-07-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_lowercase_existing_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataprotectionevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("erasure", "Erasure request actioned"),
                    ("export", "Subject access export generated"),
                    ("restriction", "Account restricted / suspended"),
                    ("unrestriction", "Account restriction lifted"),
                    ("consent_withdrawal", "Consent withdrawn"),
                    ("membership_removed", "Removed from organisation"),
                    ("rectification", "Personal data corrected by staff"),
                ],
                max_length=32,
            ),
        ),
    ]
