# Generated by Django 5.1.15 on 2026-07-31 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_lowercase_existing_emails"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationJoinRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn by requester"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional note from the requester to the organisation's administrators",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "granted_role",
                    models.CharField(
                        blank=True,
                        choices=[("ADMIN", "Admin"), ("PROJECT_MANAGER", "Project Manager")],
                        default="",
                        max_length=20,
                    ),
                ),
                ("decision_note", models.TextField(blank=True, default="")),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="join_requests_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="home.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organisation", "status", "-created_at"], name="home_organi_organis_fe7ac8_idx"
                    ),
                    models.Index(fields=["user", "status"], name="home_organi_user_id_824515_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("user", "organisation"),
                        name="unique_pending_join_request_per_user_organisation",
                    )
                ],
            },
        ),
    ]
