# Generated by Django 5.1.15 on 2026-09-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_add_organisation_merged_event_type"),
        ("home", "0016_organisationjoinrequest"),
    ]

    operations = []
