# Generated by Django 5.2.16 on 2026-09-08 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_merge_20260908_1334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="members",
            field=models.ManyToManyField(
                through="home.OrganisationMembership",
                through_fields=("organisation", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
