# Generated by Django 5.1.1 on 2024-10-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0002_answer_submitted_at_alter_answer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("multiple_choice", "Multiple Choice"),
                    ("rating", "Rating"),
                    ("boolean", "Agree/Disagree"),
                ],
                default="multiple_choice",
                max_length=50,
            ),
        ),
    ]
