# Generated by Django 5.1.1 on 2024-10-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0004_alter_question_questionnaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("text", "Text"),
                    ("multiple_choice", "Multiple Choice"),
                    ("rating", "Rating"),
                    ("boolean", "Agree/Disagree"),
                ],
                max_length=20,
            ),
        ),
    ]
