# Generated by Django 5.1.4 on 2025-01-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_surveyresponse_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='consent_config',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='demography_config',
            field=models.JSONField(null=True),
        ),
    ]
