# Generated by Django 5.1.4 on 2025-03-24 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0005_survey_consent_config_survey_demography_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=200)),
                ("path", models.CharField(max_length=255)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="survey.survey"
                    ),
                ),
            ],
        ),
    ]
