# Generated by Django 5.1.1 on 2024-10-01 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0005_question_answer_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="answer_type",
        ),
    ]
