# Generated by Django 5.1.2 on 2024-10-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0007_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="user",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.AddField(
            model_name="answer",
            name="token",
            field=models.CharField(
                blank=True, editable=False, max_length=64, unique=True
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="token",
            field=models.CharField(
                blank=True, editable=False, max_length=64, unique=True
            ),
        ),
    ]
