# Generated by Django 5.1.4 on 2025-03-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0007_remove_surveyfile_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyfile",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
