# Generated by Django 5.1.4 on 2025-03-26 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0008_alter_surveyfile_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyEvidenceSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_id", models.IntegerField(db_index=True, default=0)),
                ("text", models.TextField()),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="survey.survey"
                    ),
                ),
            ],
            options={
                "unique_together": {("survey", "section_id")},
            },
        ),
        migrations.CreateModel(
            name="SurveyEvidenceSectionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=255)),
                (
                    "evidence_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.surveyevidencesection",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
