# Generated by Django 5.1.4 on 2025-03-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0009_surveyevidencesection_surveyevidencesectionfile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SurveyEvidenceSectionFile",
            new_name="SurveyEvidenceFile",
        ),
        migrations.AddField(
            model_name="surveyevidencesection",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="surveyevidencesection",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
