# Generated by Django 5.1.4 on 2025-03-29 16:38

import django.db.models.deletion
import survey.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0012_remove_surveyevidencefile_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyevidencefile",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=survey.models.evidence_file_upload_path
            ),
        ),
        migrations.CreateModel(
            name="SurveyImprovementPlanSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_id", models.IntegerField(db_index=True, default=0)),
                ("title", models.TextField(blank=True, null=True)),
                ("plan", models.TextField(blank=True, null=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="survey.survey"
                    ),
                ),
            ],
        ),
    ]
