# Generated by Django 5.1.4 on 2025-04-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0006_survey_created_at_surveyresponse_created_at"),
        ("survey", "0013_alter_surveyevidencefile_file_and_more"),
    ]

    operations = []
