# Generated by Django 5.1.4 on 2025-04-15 14:38

# Author:   Joe Heffer <j.heffer@sheffield.ac.uk>
# Date:     15th April 2025
# Change:   Added relationship names for the survey sections
# https://docs.djangoproject.com/en/5.2/topics/db/queries/#following-relationships-backward
# This means we can do:
# survey.evidence_sections.all()

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0015_survey_survey_body_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyevidencesection",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence_sections",
                to="survey.survey",
            ),
        ),
        migrations.AlterField(
            model_name="surveyimprovementplansection",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="improvement_sections",
                to="survey.survey",
            ),
        ),
    ]
