# Generated by Django 5.1.4 on 2025-05-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0016_alter_surveyevidencesection_survey_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyevidencesection",
            name="text",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
