# Generated by Django 5.1.4 on 2025-05-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0017_alter_surveyevidencesection_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyevidencesection",
            name="text",
            field=models.TextField(
                blank=True, default="No evidence provided.", null=True
            ),
        ),
    ]
