# Generated by Django 5.1.4 on 2025-07-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0018_alter_surveyevidencesection_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Are responses being collected?"
            ),
        ),
    ]
