# Generated by Django 5.1.4 on 2025-09-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_rename_created_on_project_created_at"),
        ("survey", "0019_survey_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="survey_body_path",
            field=models.TextField(
                choices=[
                    ("NMAHPS", "NMAHPs"),
                    ("NURSES", "Nurses"),
                    ("WIDMIVES", "Midwives"),
                ],
                default="NMAHPS",
                help_text="Respondent profession",
            ),
        ),
    ]
