# Generated by Django 5.1.4 on 2025-08-26 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_rename_created_on_project_created_at"),
        ("survey", "0019_survey_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveys",
                to="home.project",
            ),
        ),
    ]
