# Generated by Django 5.1.4 on 2025-09-19 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_rename_created_on_project_created_at"),
        ("survey", "0020_alter_survey_project_alter_survey_survey_body_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="consent_config",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="demography_config",
        ),
    ]
