# Generated by Django 5.1.4 on 2025-11-07 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_rename_created_on_project_created_at"),
        ("survey", "0021_remove_survey_consent_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="is_shared",
            field=models.BooleanField(
                default=True,
                help_text="Do you accept the terms of the data sharing agreement between your organisation and the University of Sheffield?",
                verbose_name="Confirm data sharing agreement",
            ),
        )
    ]
