# Generated by Django 5.1.13 on 2026-01-07 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_project_name"),
        ("survey", "0021_remove_survey_consent_config_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="name",
            field=models.CharField(help_text="Survey title", max_length=200),
        ),
        migrations.AlterField(
            model_name="survey",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey",
                to="home.project",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="survey_body_path",
            field=models.TextField(
                choices=[
                    (
                        "NMAHPs",
                        "Nurses, Midwives and Allied Health Professionals (NMAHPs)",
                    ),
                    ("Nurses", "Nurses"),
                    ("Midwives", "Midwives"),
                ],
                default="NMAHPs",
                help_text="Respondent profession",
            ),
        ),
    ]
