# Generated by Django 5.1.4 on 2026-01-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0022_alter_survey_name_alter_survey_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="research_data_consent",
            field=models.BooleanField(
                default=False,
                help_text="Allow anonymised survey data to be shared with University of Sheffield researchers",
            ),
        ),
    ]
