# Generated by Django 5.1.4 on 2026-01-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0022_alter_survey_name_alter_survey_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="survey_body_path",
            field=models.TextField(
                choices=[
                    (
                        "NMAHPs",
                        "Nurses, Midwives and Allied Health Professionals (NMAHPs)",
                    ),
                    ("Nurses", "Nurses"),
                    ("Midwives", "Midwives"),
                    ("Nurses & Midwives", "Nurses and Midwives"),
                    ("AHP", "Allied Health Professionals (AHP)"),
                ],
                default="NMAHPs",
                help_text="Respondent profession",
            ),
        ),
    ]
