# Generated by Django 5.1.4 on 2026-01-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0022_survey_is_shared"),
        ("survey", "0023_alter_survey_survey_body_path"),
    ]

    operations = []
