# Generated by Django 5.1.13 on 2026-02-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0024_merge_20260203_1253"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="research_data_consent",
        ),
        migrations.AlterField(
            model_name="survey",
            name="is_shared",
            field=models.BooleanField(
                default=True,
                help_text="Do you accept the terms of the data sharing agreementbetween your organisation and the University of Sheffield?",
                verbose_name="Confirm data sharing agreement",
            ),
        ),
    ]
