# Generated by Django 5.1.13 on 2026-02-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0025_remove_survey_research_data_consent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="is_shared",
            field=models.BooleanField(
                default=False,
                help_text="Do you accept the terms of the data sharing agreementbetween your organisation and the University of Sheffield?",
                verbose_name="Confirm data sharing agreement",
            ),
        ),
    ]
