# Generated by Django 5.1.4 on 2026-02-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0024_merge_20260204_1206"),
        ("survey", "0026_alter_survey_is_shared"),
    ]

    operations = []
