# Generated by Django 5.1.15 on 2026-02-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0028_alter_survey_is_shared"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="is_shared",
            field=models.BooleanField(
                default=False,
                help_text="Do you accept the terms of the data sharing agreement between your organisation and the University of Sheffield?",
                verbose_name="Confirm data sharing agreement",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="survey_body_path",
            field=models.TextField(
                choices=[
                    (
                        "NMAHPs",
                        "Nurses, Midwives and Allied Health Professionals (NMAHPs)",
                    ),
                    ("Nurses", "Nurses"),
                    ("Midwives", "Midwives"),
                    ("Nurses & Midwives", "Nurses and Midwives"),
                    ("AHP", "Allied Health Professionals (AHP)"),
                    ("Generic", "Generic (Other Professional Groups)"),
                ],
                default="NMAHPs",
                help_text="Respondent profession",
            ),
        ),
    ]
