# Generated by Django 5.1.15 on 2026-02-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0029_alter_survey_is_shared"),
        ("survey", "0029_alter_survey_is_shared_alter_survey_survey_body_path"),
    ]

    operations = []
