# Generated by Django 5.1.15 on 2026-03-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0030_merge_20260217_1045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="survey_body_path",
            field=models.TextField(
                choices=[
                    (
                        "NMAHPs",
                        "Nurses, Midwives and Allied Health Professionals (NMAHPs)",
                    ),
                    ("Nurses", "Nurses"),
                    ("Midwives", "Midwives"),
                    ("Nurses & Midwives", "Nurses and Midwives"),
                    ("AHP", "Allied Health Professionals (AHP)"),
                    ("Social Prescribers", "Social Prescribers"),
                    ("Health Coaches", "Health Coaches"),
                    ("Physician Associates", "Physician Associates"),
                    ("Mental Health Practitioners", "Mental Health Practitioners"),
                    ("Practice Managers", "Practice Managers"),
                    ("Generic", "Generic (Other Professional Groups)"),
                ],
                default="NMAHPs",
                help_text="Respondent profession",
            ),
        ),
    ]
