name: Check Gunicorn configuration
on:
  push:
    branches: [ "main" ]
    paths:
      - config/**
  pull_request:
    branches: [ "main" ]
    paths:
      - config/**
permissions:
  contents: read
jobs:
  check-config:
    name: Check Gunicorn configuration
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          # This should match the version used in production
          python-version-file: .python-version
          cache: "pip"
      - name: Install dependencies
        run: pip install --requirement requirements.txt
      - name: Check Gunicorn config
        # https://docs.gunicorn.org/en/latest/configure.html
        run: gunicorn --config ./gunicorn.conf.py --check-config SORT.wsgi:application
