name: Lint Python code
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          # This should match the version used in production
          python-version: "3.12"
      - name: Install dependencies
        run: |
          # Update pip
          python -m pip install --upgrade pip
          # https://pip.pypa.io/en/stable/cli/pip_install/
          pip install --requirement requirements.txt
      - name: Run Django checks
        # https://docs.djangoproject.com/en/5.1/ref/django-admin/#check
        run: python manage.py check
