name: Run end-to-end tests
on:
  push:
    branches: [ "main" ]
    paths:
      - SORT/**
      - home/**
      - survey/**
      - e2e/**
      - ui_components/**
      - static/**
      - data/**
      - requirements*.txt
      - package*.json
      - vite.config.ts
      - .github/workflows/e2e.yaml
  pull_request:
    branches: [ "main" ]
    paths:
      - SORT/**
      - home/**
      - survey/**
      - e2e/**
      - ui_components/**
      - static/**
      - data/**
      - requirements*.txt
      - package*.json
      - vite.config.ts
      - .github/workflows/e2e.yaml
permissions:
  contents: read
jobs:
  e2e-test:
    name: Run browser tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version-file: .python-version
          cache: "pip"
      - name: Install Python dependencies
        run: pip install --requirement requirements.txt --requirement requirements-dev.txt
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: package.json
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Build front-end assets
        run: |
          npm ci
          npm run build
      # https://playwright.dev/python/docs/ci
      - name: Install Playwright browser
        run: playwright install --with-deps chromium
      - name: Run end-to-end tests
        run: |
          export DJANGO_SECRET_KEY="$(python -c "import secrets; print(secrets.token_urlsafe())")"
          python manage.py test e2e --tag=e2e --verbosity=2
      - name: Upload screenshots of failed tests
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: e2e-screenshots
          path: test-results/
          if-no-files-found: ignore
