# Lint shell scripts
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/shell-linter
name: Lint shell scripts
on:
  push:
    branches: [ "main" ]
    paths:
      - scripts/**
  pull_request:
    branches: [ "main" ]
    paths:
      - scripts/**
permissions:
  contents: read
jobs:
  lint_shell:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - uses: azohra/shell-linter@6bbeaa868df09c34ddc008e6030cfe89c03394a1 # v0.6.0
        with:
          severity: 'warning'
          exclude-paths: 'LICENSE'
