name: Lint Python code
on:
  push:
    branches: [ "main" ]
    paths:
      - SORT/**/*.py
      - home/**/*.py
      - survey/**/*.py
  pull_request:
    branches: [ "main" ]
    paths:
      - SORT/**/*.py
      - home/**/*.py
      - survey/**/*.py
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version-file: .python-version
          cache: "pip"
      - name: Install linter
        run: pip install flake8
      - name: Lint Python code
        run: flake8
